apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy1
  labels:
    app: deploy1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: deploy1
  template:
    metadata:
      name: deploy1
      labels:
        app: deploy1
    spec:
      containers:
        - name: k8s-demo-app
          image: jasonmel/k8s-demo-app:latest
          env:
            - name: MESSAGE
              value: "Hello from deploy1."
            - name: USERNAME
              valueFrom:
                configMapKeyRef:
                  name: cm1
                  key: USERNAME
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret1
                  key: PASSWORD
          ports:
            - containerPort: 80
