apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy2
  labels:
    app: deploy2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: deploy2
  template:
    metadata:
      name: deploy2
      labels:
        app: deploy2
    spec:
      containers:
        - name: k8s-demo-app
          image: jasonmel/k8s-demo-app:latest
          env:
            - name: MESSAGE
              value: "Hello from deploy2."
            - name: USERNAME
              valueFrom:
                configMapKeyRef:
                  name: cm2
                  key: USERNAME
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret2
                  key: PASSWORD
          ports:
            - containerPort: 80
