apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ing1
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: foo.bar.com
      http:
        paths:
          - path: /po1
            pathType: Prefix
            backend:
              service:
                name: po1-svc
                port:
                  number: 80
          - path: /deploy1
            pathType: Prefix
            backend:
              service:
                name: deploy1-svc
                port:
                  number: 80
